### ISSUE TITLE
POST https://domain/webauthn/register 422 at webauthn.js:159 

### ISSUE THREAD

**Issue by fidelisepeter** [Laragear/WebAuthn#21]
### Please check these requirements

- [X] This feature helps everyone using this package
- [X] It's feasible and maintainable
- [X] It's non breaking
- [ ] I issued a PR with the implementation (optional)

### Description

Please i am trying to use webauthn in my app i had to upgrade to laravel 9 to user Laragear/WebAuthn because i was unable to set up Larapass and i can't create any issue there.

Wel Successfull Set WebAuthn but having Issue registering Device...
I get 422 Error Code

And when I tried publishing the config file.

php artisan vendor:publish --provider="Laragear\WebAuthn\WebAuthnServiceProvider" --tag="config"

It doesn't work.

Please I need guidelines on how to successfully set it up

### Code sample

```php
public function register(AttestedRequest $request): Response
    {
        $request->save();

        return response()->noContent();
    }
```

**Comment by DarkGhostHunter** [comment]
Hi.

This is not a support forum. You may create a thread on other communities. 

Since it's a 422 code, it means there was a validation error, telling what failed. You can also debug if you think is an error with the library.
