### ISSUE TITLE
[2.x] Update readme to use `WebAuthnLoginController` and `WebAuthnRegisterController`

### ISSUE THREAD

**Issue by wwwDESIGN-basti** [Laragear/WebAuthn#25]
### PHP & Platform

8.1.2 & Ubuntu

### Laravel version

9

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [X] I can suggest a workaround as a Pull Request

### Expectation

-

### Description

Hey Guys,

The README file talks about an AttestationController file. This is not created during installation.

1. How do I create these?
2. How does Laravel know to speak to this controller?

### Reproduction

```php
-
```

**Comment by DarkGhostHunter** [comment]
You have to create yourself if you don't publish the included controllers. I added a clarification on the code blocks for these hypothetical controllers.

**Comment by aaronpk** [comment]
Did this file get renamed? I don't see any trace of `AttestationController` in the code anymore except for the mention in the README

**Comment by DarkGhostHunter** [comment]
@aaronpk You're right, the controllers were renamed. I'll have to fix the README.

**Comment by DarkGhostHunter** [comment]
Fixed on 3.0
