### ISSUE TITLE
alias parameter not stored in database

### ISSUE THREAD

**Issue by felix-exon** [Laragear/WebAuthn#29]
### PHP & Platform

8.1.11 - Mac OS Ventura 13.2

### Database

latest (docker)

### Laravel version

9.19

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [X] I can suggest a workaround as a Pull Request
I added the workaround/solution to this bug to #30 by mistake 😞 

### Expectation

alias should be reflected in the database but it is not.

### Description

sadly the parameter seems to be dropped.

### Reproduction

```php
const register = event => {
    event.preventDefault()
    new WebAuthn().register({
        alias: 'some alias'
    }).then(response => alert('Registration successful!'));
};


alias is sent to the options request but dropped on the way to the register request.
stored credentials do not include the given alias.

vanilla backend as described in docs `WebAuthnRegisterController.php`:
```php
    public function options(AttestationRequest $request): Responsable
    {
        return $request
            ->fastRegistration()
//            ->userless()
//            ->allowDuplicates()
            ->toCreate();
    }

    public function register(AttestedRequest $request): Response
    {
        $request->save($request->input('alias'));
        return response()->noContent();
    }

```
```


### Stack trace & logs

_No response_

**Comment by DarkGhostHunter** [comment]
I'll have to check WebAuthn API to remember what is the purpose of the alias. AFICR, it's user-land to alias the credentials.

**Comment by MordiSacks** [comment]
you are passing a string to 
`  $request->save($request->input('alias'));`
you should pass an array
`  $request->save([$request->input('alias')]);`
