### ISSUE TITLE
[X.x] What does happen that is considered an error or bug?

### ISSUE THREAD

**Issue by asivaneswaran** [Laragear/WebAuthn#35]
### PHP & Platform

8.2.1 & MacOs

### Laravel version

10

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

PhpStorm doesn't throw a warning

### Description

When I add: `// WebAuthn Routes
WebAuthn::routes();` to my routes file, I get a warning:  `Class WebAuthn is marked as @internal`

### Reproduction

```php
Import the routes in your routes files in Phpstorm
```

**Comment by DarkGhostHunter** [comment]
It's marked as `@internal` by mistake. I accccccept PRs, I'm AFK.
