### ISSUE TITLE
[1.x] Attestation Error: ByteBuffer: Invalid offset or length.

### ISSUE THREAD

**Issue by asivaneswaran** [Laragear/WebAuthn#37]
### PHP & Platform

8.2.1 & MacOs

### Laravel version

10

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

When I try to register a new device, the credential should be saved in the DB.

### Description

I am getting this error when I try to register a new device:
`Attestation Error: ByteBuffer: Invalid offset or length.`
It's coming from this class: `CompileAttestationObject` and the line number is 78.

### Reproduction

```php
Try to register a new device.
```

**Comment by DarkGhostHunter** [comment]
Insufficient information to reproduce.
