### ISSUE TITLE
[1.0] ReferenceError: WebAuthn is not defined

### ISSUE THREAD

**Issue by tobz-nz** [Laragear/WebAuthn#43]
### PHP & Platform

8.2.2

### Laravel version

10.13.5

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [x] I can suggest a workaround as a Pull Request

### Expectation

When I click the "register" or "login" buttons the `WebAuthn` class is initialised and run.

### Description

The `ReferenceError: WebAuthn is not defined` error is thrown.

I suspect this is due to Vite loading the script as `type="module"` and so the `WebAuthn` class is in a different scope.

### Reproduction

```php
after adding the code from the documentation:


<html>
<head>
@vite(['resources/js/app.js', 'resources/js/vendor/webauthn/webauthn.js'])
</head>
<body>
<form id="register-form">
    <button type="submit">Register authenticator</button>
</form>

<!-- Registering credentials -->
<script>
    const register = event => {
        event.preventDefault()

        new WebAuthn().register()
          .then(response => alert('Registration successful!'))
          .catch(error => alert('Something went wrong, try again!'))
    }

    document.getElementById('register-form').addEventListener('submit', register)
</script>
</body>
</html>


click the `Register authenticator` button.
```

**Comment by DarkGhostHunter** [comment]
I have no idea how to fix this unless a Vite expert comes around. Meanwhile, load the script directly, or copy it and assign it to the window as a property. Italo Baeza C.El 01-07-2023, a la(s) 01:37, Toby Evans ***@***.***> escribió:﻿
Assigned #43 to @DarkGhostHunter.

**Comment by tobz-nz** [comment]
I've managed to get it going by exporting the `WebAuthn` js class:

```diff
// resources/js/vendor/webauthn/webauthn.js
-class WebAuthn {
+export default class WebAuthn {
...
}
```

then importing it in the main `app.js` file & setting up events there

```javascript
// resources/js/app.js
import './bootstrap';
import WebAuthn from './vendor/webauthn/webauthn.js';

if (WebAuthn.doesntSupportWebAuthn()) {
    alert('Your device is not secure enough to use this site!');
 }

const register = event => {
    event.preventDefault()

    new WebAuthn().register()
      .then(response => alert('Registration successful!'))
      .catch(error => alert('Something went wrong, try again!'))
}

document.getElementById('register-form').addEventListener('submit', register)
```

This works, but feels a little clunky. I also have a different issue now, but I'll open another ticket for that.

I can open a PR with changes to the `webauthn.js` file and `README` if you want?

**Comment by DarkGhostHunter** [comment]
I think that exporting it will only work on modules. On vanilla JS it wouldn't work, unless you add the `WebAuthn` class to the `window` global. Can be done this on the same file? I'm AFK right now.

**Comment by tobz-nz** [comment]
Ah yeah I think you're right. 
..probably the best thing to do is just change the readme to use a `<script>` tag and not Vite.
