### ISSUE TITLE
[1.0] WebAuthn().register() throw 403 error.

### ISSUE THREAD

**Issue by tobz-nz** [Laragear/WebAuthn#46]
### PHP & Platform

8.2.2

### Laravel version

10.13.5

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

When calling `new WebAuthn().register()` the request to `/webauthn/register/options` should succeed.

### Description

But is does not:

<img width="357" alt="image" src="https://github.com/Laragear/WebAuthn/assets/443054/77af57ec-a936-435b-8b2a-de860d96c5a7">

### Reproduction

On a Fresh install, 

update vite.config.js 

```diff
-input: ['resources/css/app.css', 'resources/js/app.js'],
+input: ['resources/css/app.css', 'resources/js/app.js', 'resources/js/webauthn/webauthn.js'],
```

add `WebAuthn::routes();` to `routes/web.php`,

then create a page like:

```blade
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="preconnect" href="https://fonts.bunny.net">
    @vite('resources/js/app.js')
    <script src="{{ Vite::asset('/resources/js/vendor/webauthn/webauthn.js') }}"></script>
</head>
<body>
    <main>
        <form id="register-form">
            <button type="submit" value="Register authenticator">Register authenticator</button>
        </form>

<script defer>
if (WebAuthn.doesntSupportWebAuthn()) {
    alert('Your device is not secure enough to use this site!');
}

const register = event => {
    event.preventDefault()

    new WebAuthn().register()
      .then(response => alert('Registration successful!'))
      .catch(error => alert('Something went wrong, try again!'))
}

document.getElementById('register-form').addEventListener('submit', register)
</script>

    </main>
</body>
</html>
```

load the page page and click the button. 💥

**Comment by tobz-nz** [comment]
oh... is `register()` for existing logged in users and `login()` for new users?
That's ... confusing.

or have I got it wrong?

**Comment by DarkGhostHunter** [comment]
It's only for existing users. You can register them beforehand or even using the same data being sent as part of the Registration, using the provided tools.

Otherwise, the Attestation (registration of device) won't work because there is no User to link the public key.
