### ISSUE TITLE
[1.2.1] No way to handle validation errors

### ISSUE THREAD

**Issue by tobz-nz** [Laragear/WebAuthn#48]
### PHP & Platform

8.2.2

### Laravel version

10.13.5

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [x] I can suggest a workaround as a Pull Request

### Expectation

On a login/register options request, if validation fails, errors should be availabe in the `catch(resposne => {})` method.

### Description

On a login/register options request, if validation fails, there is no way to display the specific errors to the user.

### Reproduction

```php
new WebAuthn().login({
    email: 'not a valid email',
}, {
    remember: 'on',
}).then(response => {
    // 
})
    .catch(response => {

    if (reponse.status === 422) {

        // response.errors should be an array of errors, and response.message should be the main validation message

        let errors = response.errors;
        for (let key in errors) {
            document.getElementById(key).setCustomValidity(errors[key][0]);
            document.getElementById(key).reportValidity();
        }

        return;
    }

})
```

**Comment by tobz-nz** [comment]
I found a pretty quick/easy solution for this:

```diff
    // webauthn.js
    async login(request = {}, response = {}) {
        const optionsResponse = await this.#fetch(request, this.#routes.loginOptions);
        const json = await optionsResponse.json();

+        if (optionsResponse.status > 400) {
+            json.status = optionsResponse.status;
+            throw json;
+        }

        ...
```

Could maybe be made a little tidier but does the trick. I guess adding the same thing to the `register` method as well.

**Comment by DarkGhostHunter** [comment]
Yeah. Not a bug, because the response is received regardless of the code. Yep, you have to throw the error manually in Javascript.
