### ISSUE TITLE
[1.2.1] Custom Relying Party Id does not pass CheckRelyingPartyIdContained pipe

### ISSUE THREAD

**Issue by Bubka** [Laragear/WebAuthn#50]
### PHP & Platform

8.1.22

### Laravel version

10.16.1

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

Setting a custom Relying Party Id in the `.env` file should allow to register new webauthn devices.

### Description

Following the Laragear/webauthn documentation:
https://github.com/Laragear/WebAuthn/blob/7e62ec927e860ba73f0d2778f193ff34baa128eb/README.md?plain=1#L605-L609

If I set `WEBAUTHN_ID=https://my.domain.com` the registration ceremony fails because the RP-ID is not valid. Indeed, regarding the [Webauthn W3C recommandation](https://www.w3.org/TR/webauthn-2/#rp-id), the RP ID should be a domain, not an URL.  Using such an URL makes the webauthn API throwing a `SecurityError` (see https://www.w3.org/TR/webauthn-2/#CreateCred-DetermineRpId)

But if I set `WEBAUTHN_ID=my.domain.com`, the registration ceremony also fails but this time because the `CheckRelyingPartyIdContained` does not pass because of the way  `$current`  is defined:

https://github.com/Laragear/WebAuthn/blob/7e62ec927e860ba73f0d2778f193ff34baa128eb/src/SharedPipes/CheckRelyingPartyIdContained.php#L46-L48

Using `parse_url()` with the `PHP_URL_HOST` flag will return nothing, causing the next evaluation to fail:

https://github.com/Laragear/WebAuthn/blob/7e62ec927e860ba73f0d2778f193ff34baa128eb/src/SharedPipes/CheckRelyingPartyIdContained.php#L51-L53

### Reproduction

```php
// Set WEBAUTHN_ID=my.domain.com and try to register a new device
```

**Comment by DarkGhostHunter** [comment]
Okay. Basically, I need to fix this by extracting the domain from the `APP_URL`, and if it's empty, use `WEBAUTHN_ID` verbatim.

**Comment by asivaneswaran** [comment]
I was going to comment on it, if you look at the docs:
https://www.w3.org/TR/webauthn-2/#rp-id

It says that the relying ID can't use scheme or port. So for example, I need to pass "localhost" as the relying party ID in local,
```
$current = parse_url(
            $this->config->get('webauthn.relying_party.id') ?? $this->config->get('app.url'), PHP_URL_HOST
        );
        ```
I am not sure if you need to use APP_URL first as for example, in my case, I am using WEBAUTHN_ID to override it because I am calling it from the frontend.
I think it just needs to not use PHP_URL_HOST as it will always return null or manually add a scheme

**Comment by asivaneswaran** [comment]
@DarkGhostHunter Will you be able to create the fix for this or would you like me to create a PR for this as well?
Thanks!

**Comment by DarkGhostHunter** [comment]
Please, help me with the PR. Currently hands full.
