### ISSUE TITLE
[1.2.1] userHandle is null on webauthn.ts

### ISSUE THREAD

**Issue by asivaneswaran** [Laragear/WebAuthn#51]
### PHP & Platform

8.1.3 & MacOs

### Database

MYSQL 5

### Laravel version

Laravel 9

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

When you login with credentials, it should log the user in

### Description

I get a 422 error on login

### Reproduction

```php
Setup back and frontend and try to login.
```

### Stack trace & logs

```shell
I was able to pinpoint the issue. In the webauthn file, in the login method:


async login(request = {}, response = {}) {
        const optionsResponse = await this.#fetch(
            request,
            this.routes.loginOptions
        );
        const json = await optionsResponse.json();
        const publicKey = this.#parseIncomingServerOptions(json);
        const credentials = await navigator.credentials.get({ publicKey });
        console.log(credentials);
        const publicKeyCredential = this.#parseOutgoingCredentials(credentials);

        Object.assign(publicKeyCredential, response);

        return await this.#fetch(
            publicKeyCredential,
            this.routes.login,
            response
        ).then(WebAuthn.#handleResponse);
    }
```

THe credentials has a `userHandle` of null, so it fails the check in the backend eventually. 

Edit:
I checked that during creation, the userHandle is not even set by the navigator.

In the documentation, it does say it maybe be null:
```
For [navigator.credentials.create()](https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/create) calls made with a non-empty allowCredentials properties, the returned userHandle may be null.
```
https://developer.mozilla.org/en-US/docs/Web/API/AuthenticatorAssertionResponse/userHandle

**Comment by DarkGhostHunter** [comment]
Got it. You could make a PR as I'm hands full.
