### ISSUE TITLE
[1.2] Configuration options for WebAuthn data properties

### ISSUE THREAD

**Issue by aaronpk** [Laragear/WebAuthn#55]
### Please check these requirements

- [X] This feature helps everyone using this package
- [X] It's feasible and maintainable
- [X] It's non breaking
- [ ] I issued a PR with the implementation (optional)

### Description

It would be great if the fields used in the WebAuthn data were configurable instead of being hardcoded to the `email` and `name` properties of the user.

https://github.com/Laragear/WebAuthn/blob/1.x/src/WebAuthnAuthentication.php#L28

For example, I might want to use the user's `username` instead of `email` as the visible name of the WebAuthn credential.

It should be straightforward to add a configuration option to set these properties.

### Code sample

```php
`config/webauthn.php`


...
  'webauthn_data_properties' => [
    'name' => env('WEBAUTHN_NAME_PROP', 'email'),
    'displayName' => env('WEBAUTHN_DISPLAYNAME_PROP', 'name'),
  ]
...
```
```

**Comment by lslqtz** [comment]
I hope that the user can customize the public key generated so that the user can customize the time of its rotation and pass it to the navigator.credentials.get function for use. This is what the browser needs to autofill. (https://github.com/w3c/webauthn/wiki/Explainer:-WebAuthn-Conditional-UI)

**Comment by DarkGhostHunter** [comment]
It's not they're hard-coded. You can easily override the function with your own:

```php
    /**
     * Returns displayable data to be used to create WebAuthn Credentials.
     *
     * @return array{name: string, displayName: string}
     */
    #[ArrayShape(['name' => "string", 'displayName' => "string"])]
    public function webAuthnData(): array
    {
        return [
            'name' => $this->username,
            'displayName' => "$this->username ($this->email)",
        ];
    }
``
