### ISSUE TITLE
[1.2] Unable to Login

### ISSUE THREAD

**Issue by easydesign-coder** [Laragear/WebAuthn#57]
### PHP & Platform

8.2.8 - MacOS

### Database

MySQL 8.0.27

### Laravel version

10

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

when i try to login. but it prompt the error below.

### Description

Prompt my user table missing column. i just migrate the default db souce from package

### Reproduction

```php
i was used the default function from package
public function login(AssertedRequest $request): Response
 {
     return response()->noContent($request->login('admin') ? 204 : 422);
 }
```

### Stack trace & logs

Column not found: 1054 Unknown column 'rawId' in 'where clause' (Connection: mysql, SQL: select * from `table` where `id` = IUFjLK-rfAh7U3oV_zP_uJ6YW3umWXo3fipCY3HE6Ho and `rawId` = IUFjLK+rfAh7U3oV/zP/uJ6YW3umWXo3fipCY3HE6Ho= and `response` in (u2ghoRLl52c6KTnfJU/7W3nVPzrVuUA/98mAWWV0hw8FAAAAAA==, eyJ0eXBlIjoid2ViYXV0aG4uZ2V0IiwiY2hhbGxlbmdlIjoiX2QtNC1tVjJfUEVueUFTZkJHNnBRdyIsIm9yaWdpbiI6Imh0dHBzOi8vYmFzZS10ZW1wbGF0ZS50ZXN0IiwiY3Jvc3NPcmlnaW4iOmZhbHNlfQ==, MEYCIQDhaC21Gjmin6oB9tyvrQJSsrukRNcscvd8s36HRxrT+AIhAL3RS6G4idm6mgfoWeak8SIgtJla++A4saiAznGWV6ih, a07bc26051d04b909c9dfce9f9068255) and `type` = public-key limit 1)

**Comment by DarkGhostHunter** [comment]
This will happen if you don't set the `WebAuthnUserProvider` as the README says.
