### ISSUE TITLE
Assertion Error: User ID is not owner of the stored credential.  Login Error

### ISSUE THREAD

**Issue by RealMrHex** [Laragear/WebAuthn#59]
### PHP & Platform

8.2

### Laravel version

10 [Latest]

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

I want to login.

### Description

When I attempted to log in using my Android device with a QR code, an error message appeared is Laravel Log files:

"Assertion Error: User ID is not the owner of the stored credential."

The userHandle is null. I tried the codes in the PRs and the Android null repository.

### Reproduction

```php
...
```

**Comment by RealMrHex** [comment]
Is there any workaround or fix available? @DarkGhostHunter

**Comment by DarkGhostHunter** [comment]
I'm currently working on something else to answer.

**Comment by DarkGhostHunter** [comment]
It's fixed in #52
