### ISSUE TITLE
[1.x] Fails to register yubikey (or platform authenticator) when using @simplewebauthn/browser

### ISSUE THREAD

**Issue by matthijs** [Laragear/WebAuthn#63]
### PHP & Platform

8.1 (Debian - Bookworm)

### Database

PostgreSQL 15

### Laravel version

10.40.0

### Have you done this?

- [X] I have checked my logs and I'm sure is a bug in this package.
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

When I am trying to register a yubikey, I expect it to be registered with my account.

### Description

Impossible to register my yubikey (or any platform authenticator, in my case Touch ID).

I guess that the javascript used in [@simplewebauthn/browser](https://simplewebauthn.dev/docs/packages/browser) is a bit different which causes this issue.

### Reproduction

```php
I've used the following example https://github.com/MasterKale/SimpleWebAuthn/blob/master/example/public/index.html

Adjusted the urls and tried to register a yubikey and tried to register Touch ID.
```

### Stack trace & logs

```shell
When trying to register I get the following validation error:

ByteBuffer: Invalid offset or length.
```

**Comment by DarkGhostHunter** [comment]
Going to leave this open when I come back for WebAuthn.

**Comment by DarkGhostHunter** [comment]
Cannot reproduce, no stacktrace.
